[[remove]]
directory = "test\\"

[[check]]
type = "Exclude"
id = "STAN-0103"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0203"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0208"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0213"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0302"
scope = "all" 

[[check]]
type = "Exclude"
id = "STAN-0212"
file = "src\\Predicate\\Util.hs"

