name:                predicate-typed
version:             0.3.0.0
github:              "gbwey/predicate-typed"
synopsis:            Predicates, Refinement types and Dsl
category:            Data
license:             BSD3
author:              "Grant Weyburne <gbwey9@gmail.com>"
maintainer:          "Grant Weyburne <gbwey9@gmail.com>"
copyright:           "Copyright 2019, Grant Weyburne"

description:         Please see the README on GitHub at <https://github.com/gbwey/predicate-typed#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- aeson
- assoc >= 1
- binary
- bytestring
- comonad
- containers
- deepseq
- directory
- ghc-prim
- lens
- mtl
- pcre-heavy >= 1.0.0.2
- pcre-light
- pretty
- pretty-terminal >= 0.1.0.0
- safe
- template-haskell
- text
- th-lift >= 0.8.0.1
- these >= 1.0.0
- time
- tree-view >= 0.5

library:
  source-dirs: src
  ghc-options:
  - -fomit-interface-pragmas

tests:
  predicate-typed-test:
    main:                TestSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fomit-interface-pragmas
    dependencies:
    - predicate-typed
    - stm
    - tasty
    - tasty-hunit
    - tasty-quickcheck
  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options:
    - -threaded
    - -fomit-interface-pragmas
    source-dirs:
    - .
    - src
    dependencies:
    - predicate-typed
    - doctest
