name:                predicate-typed
version:             0.6.3.0
github:              "gbwey/predicate-typed"
synopsis:            Predicates, Refinement types and Dsl
category:            Data
license:             BSD3
author:              "Grant Weyburne <gbwey9@gmail.com>"
maintainer:          "Grant Weyburne <gbwey9@gmail.com>"
copyright:           "Copyright 2019, Grant Weyburne"

description:         Please see the README on GitHub at <https://github.com/gbwey/predicate-typed#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- aeson
- binary
- bytestring
- comonad
- containers
- deepseq
- directory
- ghc-prim
- hashable
- lens
- mtl
- pcre-heavy >= 1.0.0.2
- pcre-light
- pretty
- pretty-terminal >= 0.1.0.0
- safe
- template-haskell
- text
- th-lift
- these
- time
- tree-view >= 0.5

library:
  source-dirs: src

  ghc-options:
#  - -fomit-interface-pragmas
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
#  - -Widentities
#  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  when:
     condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie

tests:
  predicate-typed-test:
    main:                TestSpec.hs
    source-dirs:
#    - src
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
#    - -fomit-interface-pragmas
#    - -Wno-missing-export-lists
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
    dependencies:
    - base
    - predicate-typed
    - stm
    - tasty
    - tasty-hunit
    - tasty-quickcheck
  doctests:
    main: doctests.hs
    source-dirs:
    - src
    - doctest
#    other-modules: []
    ghc-options:
    - -threaded
#    - -fomit-interface-pragmas
#    - -Wno-missing-export-lists
    when:
       condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie

    dependencies:
    - base
    - predicate-typed
    - doctest
