name:                predicate-typed
version:             0.1.0.1
github:              "github.com/gbwey/predicate-typed"
synopsis:            Predicates, Refinement types and Dsl
license:             BSD3
author:              "Grant Weyburne"
maintainer:          "gbwey9@gmail.com"
copyright:           "2019 gbwey"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/gbwey/predicate-typed#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- aeson
- binary
- bytestring
- comonad
- containers
- deepseq
- directory
- ghc-prim
- lens
- mtl
- pcre-heavy
- pcre-light
- pretty
- pretty-terminal
- safe
- semialign
- template-haskell
- text
- th-lift
- th-orphans
- these
- these-lens
- time
- tree-view

library:
  source-dirs: src
  ghc-options:
  - -fomit-interface-pragmas

tests:
  predicate-typed-test:
    main:                TestSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fomit-interface-pragmas
    dependencies:
    - predicate-typed
    - stm
    - tasty
    - tasty-hunit
    - tasty-quickcheck
  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options:
    - -threaded
    - -fomit-interface-pragmas
    source-dirs:
    - .
    - src
    dependencies:
    - predicate-typed
    - doctest
