name:                predicate-typed
version:             0.7.4.0
github:              gbwey/predicate-typed
synopsis:            Predicates, Refinement types and Dsl
category:            Data
license:             BSD3
author:              gbwey
maintainer:          gbwey
copyright:           2019 Grant Weyburne

description:         Please see the README on GitHub at <https://github.com/gbwey/predicate-typed#readme>

flags:
  coverage:
    description: run hpc tool and put files in separate folders
    manual: yes
    default: no

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- aeson
- aeson-pretty
- binary
- bytestring
- comonad
- containers
- deepseq
- directory
- hashable
- lens
- mtl
- pcre-heavy >= 1.0.0.2
- pcre-light
- pretty-terminal >= 0.1.0.0
- safe
- string-conversions
- template-haskell
- text
- th-lift
- these >= 0.8
- time
- transformers

library:
  source-dirs: src

  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  when:
   - condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie
     - -Widentities
   - condition: flag(coverage)
     ghc-options:
     - -fhpc
     - -hpcdir hpc/lib/

tests:
  predicate-typed-test:
    main:                TestSpec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
    -  condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
       - -Widentities
    -  condition: flag(coverage)
       ghc-options:
       - -fhpc
       - -hpcdir hpc/testspec/
    dependencies:
    - base
    - predicate-typed
    - stm
    - tasty
    - tasty-hunit
    - tasty-quickcheck
  doctests:
    main: doctests.hs
    source-dirs:
    - doctest
    ghc-options:
    - -Wall
    - -threaded
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
    -  condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
       - -Widentities
    -  condition: flag(coverage)
       ghc-options:
       - -fhpc
       - -hpcdir hpc/doctest/

    dependencies:
    - base
    - predicate-typed
    - doctest
